#ifndef __bpmainframe__
#define __bpmainframe__

/**
@file
Subclass of BpMainFrameBase, which is generated by wxFormBuilder.
*/

#include "bp_gui.h"

namespace bestpractice
{


/** Implementing BpMainFrameBase */
class BpMainFrame : public BpMainFrameBase
{
protected:
	// Handlers for BpMainFrameBase events.
	void pitchResetClick( wxCommandEvent& event );
	void finePitchResetClick( wxCommandEvent& event );
	void speedResetClick( wxCommandEvent& event );
	void FlatBtnClick( wxCommandEvent& event );
	void prevClick( wxCommandEvent& event );
	void playClick( wxCommandEvent& event );
	void pauseClick( wxCommandEvent& event );
	void nextClick( wxCommandEvent& event );
	void loopStartNowClick( wxCommandEvent& event );
	void loopEndNowClick( wxCommandEvent& event );
	void OpenFile( wxCommandEvent& event );
	void OpenDisc( wxCommandEvent& event );
	void SaveAs( wxCommandEvent& event );
	void SaveLoopPoints( wxCommandEvent& event );
	void CheckCDDB( wxCommandEvent& event );
	void AboutMenu( wxCommandEvent& event );

public:
	/** Constructor */
	BpMainFrame( wxWindow* parent );
};

} //namespace

#endif // __bpmainframe__
