#ifndef __bpmainframebase__
#define __bpmainframebase__

/**
@file
Subclass of BpMainFrameBase, which is generated by wxFormBuilder.
*/

#include "bp_gui.h"

namespace bestpractice
{

    /** Implementing BpMainFrameBase */
    class BpMainFrame : public BpMainFrameBase
    {
    public:
        /** Constructor */
        BpMainFrame( wxWindow* parent );
    };
}
#endif // __bpmainframebase__
