#ifndef __bpmainframe__
#define __bpmainframe__

/**
@file
Subclass of BpMainFrameBase, which is generated by wxFormBuilder.
*/

#include "bp_gui.h"
#include "bpFSM.h"

// Forward declaration
typedef void PaStream;

BEGIN_DECLARE_EVENT_TYPES()
DECLARE_EVENT_TYPE(wxEVT_STOP_FSM, -1)
END_DECLARE_EVENT_TYPES()

namespace bestpractice
{


/** Implementing BpMainFrameBase */
class BpMainFrame : public BpMainFrameBase
{
    PaStream *stream;
    bpFSM bp_state;
    int fd;

    friend void portaudioStreamFinished(void*);

    void EventStopFSM( wxCommandEvent& event );

protected:
	// Handlers for BpMainFrameBase events.
	void pitchResetClick( wxCommandEvent& event );
	void finePitchResetClick( wxCommandEvent& event );
	void speedResetClick( wxCommandEvent& event );
	void FlatBtnClick( wxCommandEvent& event );
	void prevClick( wxCommandEvent& event );
	void playClick( wxCommandEvent& event );
	void pauseClick( wxCommandEvent& event );
	void nextClick( wxCommandEvent& event );
	void loopStartNowClick( wxCommandEvent& event );
	void loopEndNowClick( wxCommandEvent& event );
	void OpenFile( wxCommandEvent& event );
	void OpenDisc( wxCommandEvent& event );
	void SaveAs( wxCommandEvent& event );
	void SaveLoopPoints( wxCommandEvent& event );
	void CheckCDDB( wxCommandEvent& event );
	void AboutMenu( wxCommandEvent& event );

public:
	/** Constructor */
	BpMainFrame( wxWindow* parent );
	~BpMainFrame();

	bool InitializeAudioStreamFromFile( const wxString& filename);
	bool NextAudioFileAvailable();
	bool PreviousAudioFileAvailable();
	bool UninitializeAudioStream();
	void ContinueStream();
	void PauseStream();
	const wxString GetNextAudioFileName();
	const wxString GetPreviousAudioFileName();

};

} //namespace

#endif // __bpmainframe__
