PortAudioCpp: portaudio::impl Namespace Reference
portaudio::impl Namespace Reference
Functions
int callbackInterfaceToPaCallbackAdapter (const void *inputBuffer, void *outputBuffer, unsigned long numFrames, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
int cppCallbackToPaCallbackAdapter (const void *inputBuffer, void *outputBuffer, unsigned long numFrames, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
Function Documentation
int portaudio::impl::callbackInterfaceToPaCallbackAdapter (const void * inputBuffer, void * outputBuffer, unsigned long numFrames, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData)
Adapts any CallbackInterface object to a C-callable function (ie this function). A pointer to the object should be passed as ``userData'' when setting up the callback.
Referenced by portaudio::MemFunCallbackStream< T >::open(), and portaudio::InterfaceCallbackStream::open().
int portaudio::impl::cppCallbackToPaCallbackAdapter (const void * inputBuffer, void * outputBuffer, unsigned long numFrames, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData)
Adapts any a C++ callback to a C-callable function (ie this function). A pointer to a struct with the C++ function pointer and the actual user data should be passed as the ``userData'' parameter when setting up the callback.
Referenced by portaudio::FunCallbackStream::open().