PortAudioCpp: portaudio::InterfaceCallbackStream Class Reference
portaudio::InterfaceCallbackStream Class Reference
Callback stream using an instance of an object that's derived from the CallbackInterface interface.
#include <InterfaceCallbackStream.hxx>
Public Member Functions
InterfaceCallbackStream ()
InterfaceCallbackStream (const StreamParameters &parameters, CallbackInterface &instance)
~InterfaceCallbackStream ()
void open (const StreamParameters &parameters, CallbackInterface &instance)
Private Member Functions
InterfaceCallbackStream (const InterfaceCallbackStream &)
InterfaceCallbackStream & operator= (const InterfaceCallbackStream &)
Detailed Description
Callback stream using an instance of an object that's derived from the CallbackInterface interface.
Constructor & Destructor Documentation
portaudio::InterfaceCallbackStream::InterfaceCallbackStream ()
portaudio::InterfaceCallbackStream::InterfaceCallbackStream (const StreamParameters & parameters, CallbackInterface & instance)
References open().
portaudio::InterfaceCallbackStream::~InterfaceCallbackStream ()
References portaudio::Stream::close().
portaudio::InterfaceCallbackStream::InterfaceCallbackStream (const InterfaceCallbackStream &) [private]
Member Function Documentation
void portaudio::InterfaceCallbackStream::open (const StreamParameters & parameters, CallbackInterface & instance)
References portaudio::impl::callbackInterfaceToPaCallbackAdapter(), portaudio::StreamParameters::flags(), portaudio::StreamParameters::framesPerBuffer(), portaudio::StreamParameters::inputParameters(), portaudio::StreamParameters::outputParameters(), portaudio::DirectionSpecificStreamParameters::paStreamParameters(), portaudio::StreamParameters::sampleRate(), and portaudio::Stream::stream_.
Referenced by InterfaceCallbackStream().
InterfaceCallbackStream& portaudio::InterfaceCallbackStream::operator= (const InterfaceCallbackStream &) [private]
The documentation for this class was generated from the following files:
InterfaceCallbackStream.hxx
InterfaceCallbackStream.cxx