PortAudioCpp: portaudio::FunCallbackStream Class Reference
portaudio::FunCallbackStream Class Reference
Callback stream using a C++ function (either a free function or a static function) callback.
#include <CppFunCallbackStream.hxx>
Classes
struct CppToCCallbackData
Simple structure containing a function pointer to the C++ callback function and a (void) pointer to the user supplied data.
Public Types
typedef int(* CallbackFunPtr)(const void *inputBuffer, void *outputBuffer, unsigned long numFrames, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
Public Member Functions
FunCallbackStream ()
FunCallbackStream (const StreamParameters &parameters, CallbackFunPtr funPtr, void *userData)
~FunCallbackStream ()
void open (const StreamParameters &parameters, CallbackFunPtr funPtr, void *userData)
Private Member Functions
FunCallbackStream (const FunCallbackStream &)
FunCallbackStream & operator= (const FunCallbackStream &)
void open (const StreamParameters &parameters)
Private Attributes
CppToCCallbackData adapterData_
Detailed Description
Callback stream using a C++ function (either a free function or a static function) callback.
Member Typedef Documentation
typedef int(* portaudio::FunCallbackStream::CallbackFunPtr)(const void *inputBuffer, void *outputBuffer, unsigned long numFrames, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
Constructor & Destructor Documentation
portaudio::FunCallbackStream::FunCallbackStream ()
portaudio::FunCallbackStream::FunCallbackStream (const StreamParameters & parameters, CallbackFunPtr funPtr, void * userData)
References open().
portaudio::FunCallbackStream::~FunCallbackStream ()
References portaudio::Stream::close().
portaudio::FunCallbackStream::FunCallbackStream (const FunCallbackStream &) [private]
Member Function Documentation
void portaudio::FunCallbackStream::open (const StreamParameters & parameters, CallbackFunPtr funPtr, void * userData)
References adapterData_, and portaudio::FunCallbackStream::CppToCCallbackData::init().
Referenced by FunCallbackStream().
FunCallbackStream& portaudio::FunCallbackStream::operator= (const FunCallbackStream &) [private]
void portaudio::FunCallbackStream::open (const StreamParameters & parameters) [private]
References adapterData_, portaudio::impl::cppCallbackToPaCallbackAdapter(), portaudio::StreamParameters::flags(), portaudio::StreamParameters::framesPerBuffer(), portaudio::StreamParameters::inputParameters(), portaudio::StreamParameters::outputParameters(), portaudio::DirectionSpecificStreamParameters::paStreamParameters(), portaudio::StreamParameters::sampleRate(), and portaudio::Stream::stream_.
Member Data Documentation
CppToCCallbackData portaudio::FunCallbackStream::adapterData_ [private]
Referenced by open().
The documentation for this class was generated from the following files:
CppFunCallbackStream.hxx
CppFunCallbackStream.cxx