PortAudioCpp: portaudio::MemFunCallbackStream< T > Class Template Reference
portaudio::MemFunCallbackStream< T > Class Template Reference
Callback stream using a class's member function as a callback. Template argument T is the type of the class of which a member function is going to be used.
#include <MemFunCallbackStream.hxx>
Classes
class MemFunToCallbackInterfaceAdapter
Inner class which adapts a member function callback to a CallbackInterface compliant class (so it can be adapted using the paCallbackAdapter function).
Public Types
typedef int(T::* CallbackFunPtr)(const void *, void *, unsigned long, const PaStreamCallbackTimeInfo *, PaStreamCallbackFlags)
Public Member Functions
MemFunCallbackStream ()
MemFunCallbackStream (const StreamParameters &parameters, T &instance, CallbackFunPtr memFun)
~MemFunCallbackStream ()
void open (const StreamParameters &parameters, T &instance, CallbackFunPtr memFun)
Private Member Functions
MemFunCallbackStream (const MemFunCallbackStream &)
MemFunCallbackStream & operator= (const MemFunCallbackStream &)
void open (const StreamParameters &parameters)
Private Attributes
MemFunToCallbackInterfaceAdapter adapter_
Detailed Description
template<typename T>
class portaudio::MemFunCallbackStream< T >
Callback stream using a class's member function as a callback. Template argument T is the type of the class of which a member function is going to be used.
Example usage:
MemFunCallback<MyClass> stream = MemFunCallbackStream(parameters, *this, &MyClass::myCallbackFunction);
Member Typedef Documentation
template<typename T > typedef int(T::* portaudio::MemFunCallbackStream< T >::CallbackFunPtr)(const void *, void *, unsigned long, const PaStreamCallbackTimeInfo *, PaStreamCallbackFlags)
Constructor & Destructor Documentation
template<typename T > portaudio::MemFunCallbackStream< T >::MemFunCallbackStream () [inline]
template<typename T > portaudio::MemFunCallbackStream< T >::MemFunCallbackStream (const StreamParameters & parameters, T & instance, CallbackFunPtr memFun) [inline]
References portaudio::MemFunCallbackStream< T >::open().
template<typename T > portaudio::MemFunCallbackStream< T >::~MemFunCallbackStream () [inline]
References portaudio::Stream::close().
template<typename T > portaudio::MemFunCallbackStream< T >::MemFunCallbackStream (const MemFunCallbackStream< T > &) [private]
Member Function Documentation
template<typename T > void portaudio::MemFunCallbackStream< T >::open (const StreamParameters & parameters, T & instance, CallbackFunPtr memFun) [inline]
References portaudio::MemFunCallbackStream< T >::adapter_, and portaudio::MemFunCallbackStream< T >::MemFunToCallbackInterfaceAdapter::init().
Referenced by portaudio::MemFunCallbackStream< T >::MemFunCallbackStream().
template<typename T > MemFunCallbackStream& portaudio::MemFunCallbackStream< T >::operator= (const MemFunCallbackStream< T > &) [private]
template<typename T > void portaudio::MemFunCallbackStream< T >::open (const StreamParameters & parameters) [inline, private]
References portaudio::MemFunCallbackStream< T >::adapter_, portaudio::impl::callbackInterfaceToPaCallbackAdapter(), portaudio::StreamParameters::flags(), portaudio::StreamParameters::framesPerBuffer(), portaudio::StreamParameters::inputParameters(), portaudio::StreamParameters::outputParameters(), portaudio::DirectionSpecificStreamParameters::paStreamParameters(), portaudio::StreamParameters::sampleRate(), and portaudio::Stream::stream_.
Member Data Documentation
template<typename T > MemFunToCallbackInterfaceAdapter portaudio::MemFunCallbackStream< T >::adapter_ [private]
Referenced by portaudio::MemFunCallbackStream< T >::open().
The documentation for this class was generated from the following file:
MemFunCallbackStream.hxx