PortAudioCpp: portaudio::CFunCallbackStream Class Reference
portaudio::CFunCallbackStream Class Reference
Callback stream using a free function with C linkage. It's important that the function the passed function pointer points to is declared ``extern "C"''.
#include <CFunCallbackStream.hxx>
Public Member Functions
CFunCallbackStream ()
CFunCallbackStream (const StreamParameters &parameters, PaStreamCallback *funPtr, void *userData)
~CFunCallbackStream ()
void open (const StreamParameters &parameters, PaStreamCallback *funPtr, void *userData)
Private Member Functions
CFunCallbackStream (const CFunCallbackStream &)
CFunCallbackStream & operator= (const CFunCallbackStream &)
Detailed Description
Callback stream using a free function with C linkage. It's important that the function the passed function pointer points to is declared ``extern "C"''.
Constructor & Destructor Documentation
portaudio::CFunCallbackStream::CFunCallbackStream ()
portaudio::CFunCallbackStream::CFunCallbackStream (const StreamParameters & parameters, PaStreamCallback * funPtr, void * userData)
References open().
portaudio::CFunCallbackStream::~CFunCallbackStream ()
References portaudio::Stream::close().
portaudio::CFunCallbackStream::CFunCallbackStream (const CFunCallbackStream &) [private]
Member Function Documentation
void portaudio::CFunCallbackStream::open (const StreamParameters & parameters, PaStreamCallback * funPtr, void * userData)
References portaudio::StreamParameters::flags(), portaudio::StreamParameters::framesPerBuffer(), portaudio::StreamParameters::inputParameters(), portaudio::StreamParameters::outputParameters(), portaudio::DirectionSpecificStreamParameters::paStreamParameters(), portaudio::StreamParameters::sampleRate(), and portaudio::Stream::stream_.
Referenced by CFunCallbackStream().
CFunCallbackStream& portaudio::CFunCallbackStream::operator= (const CFunCallbackStream &) [private]
The documentation for this class was generated from the following files:
CFunCallbackStream.hxx
CFunCallbackStream.cxx