PortAudioCpp: portaudio::DirectionSpecificStreamParameters Class Reference
portaudio::DirectionSpecificStreamParameters Class Reference
All parameters for one direction (either in or out) of a Stream. Together with parameters common to both directions, two DirectionSpecificStreamParameters can make up a StreamParameters object which contains all parameters for a Stream.
#include <DirectionSpecificStreamParameters.hxx>
Public Member Functions
DirectionSpecificStreamParameters ()
DirectionSpecificStreamParameters (const Device &device, int numChannels, SampleDataFormat format, bool interleaved, PaTime suggestedLatency, void *hostApiSpecificStreamInfo)
void setDevice (const Device &device)
void setNumChannels (int numChannels)
void setSampleFormat (SampleDataFormat format, bool interleaved=true)
void setHostApiSpecificSampleFormat (PaSampleFormat format, bool interleaved=true)
void setSuggestedLatency (PaTime latency)
void setHostApiSpecificStreamInfo (void *streamInfo)
PaStreamParameters * paStreamParameters ()
const PaStreamParameters * paStreamParameters () const
Device & device () const
int numChannels () const
SampleDataFormat sampleFormat () const
bool isSampleFormatInterleaved () const
bool isSampleFormatHostApiSpecific () const
PaSampleFormat hostApiSpecificSampleFormat () const
PaTime suggestedLatency () const
void * hostApiSpecificStreamInfo () const
Static Public Member Functions
static
DirectionSpecificStreamParameters null ()
Private Attributes
PaStreamParameters paStreamParameters_
Detailed Description
All parameters for one direction (either in or out) of a Stream. Together with parameters common to both directions, two DirectionSpecificStreamParameters can make up a StreamParameters object which contains all parameters for a Stream.
Constructor & Destructor Documentation
portaudio::DirectionSpecificStreamParameters::DirectionSpecificStreamParameters ()
Default constructor -- all parameters will be uninitialized.
portaudio::DirectionSpecificStreamParameters::DirectionSpecificStreamParameters (const Device & device, int numChannels, SampleDataFormat format, bool interleaved, PaTime suggestedLatency, void * hostApiSpecificStreamInfo)
Constructor which sets all required fields.
References setDevice(), setHostApiSpecificStreamInfo(), setNumChannels(), setSampleFormat(), and setSuggestedLatency().
Member Function Documentation
DirectionSpecificStreamParameters portaudio::DirectionSpecificStreamParameters::null () [static]
Returns a `nil' DirectionSpecificStreamParameters object. This can be used to specify that one direction of a Stream is not required (i.e. when creating a half-duplex Stream). All fields of the null DirectionSpecificStreamParameters object are invalid except for the device and the number of channel, which are set to paNoDevice and 0 respectively.
References paStreamParameters_.
void portaudio::DirectionSpecificStreamParameters::setDevice (const Device & device)
References portaudio::Device::index(), and paStreamParameters_.
Referenced by DirectionSpecificStreamParameters().
void portaudio::DirectionSpecificStreamParameters::setNumChannels (int numChannels)
References paStreamParameters_.
Referenced by DirectionSpecificStreamParameters().
void portaudio::DirectionSpecificStreamParameters::setSampleFormat (SampleDataFormat format, bool interleaved = true)
References paStreamParameters_.
Referenced by DirectionSpecificStreamParameters().
void portaudio::DirectionSpecificStreamParameters::setHostApiSpecificSampleFormat (PaSampleFormat format, bool interleaved = true)
References paStreamParameters_.
void portaudio::DirectionSpecificStreamParameters::setSuggestedLatency (PaTime latency)
References paStreamParameters_.
Referenced by DirectionSpecificStreamParameters().
void portaudio::DirectionSpecificStreamParameters::setHostApiSpecificStreamInfo (void * streamInfo)
References paStreamParameters_.
Referenced by DirectionSpecificStreamParameters().
PaStreamParameters * portaudio::DirectionSpecificStreamParameters::paStreamParameters ()
References paStreamParameters_.
Referenced by portaudio::StreamParameters::isSupported(), portaudio::MemFunCallbackStream< T >::open(), portaudio::InterfaceCallbackStream::open(), portaudio::FunCallbackStream::open(), portaudio::CFunCallbackStream::open(), and portaudio::BlockingStream::open().
const PaStreamParameters * portaudio::DirectionSpecificStreamParameters::paStreamParameters () const
References paStreamParameters_.
Device & portaudio::DirectionSpecificStreamParameters::device () const
References portaudio::System::deviceByIndex(), portaudio::System::instance(), and paStreamParameters_.
int portaudio::DirectionSpecificStreamParameters::numChannels () const
References paStreamParameters_.
SampleDataFormat portaudio::DirectionSpecificStreamParameters::sampleFormat () const
Returns the (non host api-specific) sample format, without including the paNonInterleaved flag. If the sample format is host api-spefific, INVALID_FORMAT (0) will be returned.
References portaudio::INVALID_FORMAT, isSampleFormatHostApiSpecific(), and paStreamParameters_.
bool portaudio::DirectionSpecificStreamParameters::isSampleFormatInterleaved () const
References paStreamParameters_.
bool portaudio::DirectionSpecificStreamParameters::isSampleFormatHostApiSpecific () const
References paStreamParameters_.
Referenced by hostApiSpecificSampleFormat(), and sampleFormat().
PaSampleFormat portaudio::DirectionSpecificStreamParameters::hostApiSpecificSampleFormat () const
Returns the host api-specific sample format, without including any paCustomFormat or paNonInterleaved flags. Will return 0 if the sample format is not host api-specific.
References isSampleFormatHostApiSpecific(), and paStreamParameters_.
PaTime portaudio::DirectionSpecificStreamParameters::suggestedLatency () const
References paStreamParameters_.
void * portaudio::DirectionSpecificStreamParameters::hostApiSpecificStreamInfo () const
References paStreamParameters_.
Member Data Documentation
PaStreamParameters portaudio::DirectionSpecificStreamParameters::paStreamParameters_ [private]
Referenced by device(), hostApiSpecificSampleFormat(), hostApiSpecificStreamInfo(), isSampleFormatHostApiSpecific(), isSampleFormatInterleaved(), null(), numChannels(), paStreamParameters(), sampleFormat(), setDevice(), setHostApiSpecificSampleFormat(), setHostApiSpecificStreamInfo(), setNumChannels(), setSampleFormat(), setSuggestedLatency(), and suggestedLatency().
The documentation for this class was generated from the following files:
DirectionSpecificStreamParameters.hxx
DirectionSpecificStreamParameters.cxx