PortAudioCpp: portaudio::BlockingStream Class Reference
portaudio::BlockingStream Class Reference
Stream class for blocking read/write-style input and output.
#include <BlockingStream.hxx>
Public Member Functions
BlockingStream ()
BlockingStream (const StreamParameters &parameters)
~BlockingStream ()
void open (const StreamParameters &parameters)
void read (void *buffer, unsigned long numFrames)
void write (const void *buffer, unsigned long numFrames)
signed long availableReadSize () const
signed long availableWriteSize () const
Private Member Functions
BlockingStream (const BlockingStream &)
BlockingStream & operator= (const BlockingStream &)
Detailed Description
Stream class for blocking read/write-style input and output.
Constructor & Destructor Documentation
portaudio::BlockingStream::BlockingStream ()
portaudio::BlockingStream::BlockingStream (const StreamParameters & parameters)
References open().
portaudio::BlockingStream::~BlockingStream ()
References portaudio::Stream::close().
portaudio::BlockingStream::BlockingStream (const BlockingStream &) [private]
Member Function Documentation
void portaudio::BlockingStream::open (const StreamParameters & parameters)
References portaudio::StreamParameters::flags(), portaudio::StreamParameters::framesPerBuffer(), portaudio::StreamParameters::inputParameters(), portaudio::StreamParameters::outputParameters(), portaudio::DirectionSpecificStreamParameters::paStreamParameters(), portaudio::StreamParameters::sampleRate(), and portaudio::Stream::stream_.
Referenced by BlockingStream().
void portaudio::BlockingStream::read (void * buffer, unsigned long numFrames)
References portaudio::Stream::stream_.
void portaudio::BlockingStream::write (const void * buffer, unsigned long numFrames)
References portaudio::Stream::stream_.
signed long portaudio::BlockingStream::availableReadSize () const
References portaudio::Stream::stream_.
signed long portaudio::BlockingStream::availableWriteSize () const
References portaudio::Stream::stream_.
BlockingStream& portaudio::BlockingStream::operator= (const BlockingStream &) [private]
The documentation for this class was generated from the following files:
BlockingStream.hxx
BlockingStream.cxx