PortAudioCpp: portaudio::StreamParameters Class Reference
portaudio::StreamParameters Class Reference
The entire set of parameters needed to configure and open a Stream.
#include <StreamParameters.hxx>
Public Member Functions
StreamParameters ()
StreamParameters (const DirectionSpecificStreamParameters &inputParameters, const DirectionSpecificStreamParameters &outputParameters, double sampleRate, unsigned long framesPerBuffer, PaStreamFlags flags)
void setInputParameters (const DirectionSpecificStreamParameters &parameters)
void setOutputParameters (const DirectionSpecificStreamParameters &parameters)
void setSampleRate (double sampleRate)
void setFramesPerBuffer (unsigned long framesPerBuffer)
void setFlag (PaStreamFlags flag)
void unsetFlag (PaStreamFlags flag)
void clearFlags ()
bool isSupported () const
DirectionSpecificStreamParameters & inputParameters ()
const
DirectionSpecificStreamParameters & inputParameters () const
DirectionSpecificStreamParameters & outputParameters ()
const
DirectionSpecificStreamParameters & outputParameters () const
double sampleRate () const
unsigned long framesPerBuffer () const
PaStreamFlags flags () const
bool isFlagSet (PaStreamFlags flag) const
Private Attributes
DirectionSpecificStreamParameters inputParameters_
DirectionSpecificStreamParameters outputParameters_
double sampleRate_
unsigned long framesPerBuffer_
PaStreamFlags flags_
Detailed Description
The entire set of parameters needed to configure and open a Stream.
It contains parameters of input, output and shared parameters. Using the isSupported() method, the StreamParameters can be checked if opening a Stream using this StreamParameters would succeed or not. Accessors are provided to higher-level parameters aswell as the lower-level parameters which are mainly intended for internal use.
Constructor & Destructor Documentation
portaudio::StreamParameters::StreamParameters ()
Default constructor; does nothing.
portaudio::StreamParameters::StreamParameters (const DirectionSpecificStreamParameters & inputParameters, const DirectionSpecificStreamParameters & outputParameters, double sampleRate, unsigned long framesPerBuffer, PaStreamFlags flags)
Sets up the all parameters needed to open either a half-duplex or full-duplex Stream.
Parameters:
inputParameters The parameters for the input direction of the to-be opened Stream or DirectionSpecificStreamParameters::null() for an output-only Stream.
outputParameters The parameters for the output direction of the to-be opened Stream or DirectionSpecificStreamParameters::null() for an input-only Stream.
sampleRate The to-be opened Stream's sample rate in Hz.
framesPerBuffer The number of frames per buffer for a CallbackStream, or the preferred buffer granularity for a BlockingStream.
flags The flags for the to-be opened Stream; default paNoFlag.
Member Function Documentation
void portaudio::StreamParameters::setInputParameters (const DirectionSpecificStreamParameters & parameters)
References inputParameters_.
void portaudio::StreamParameters::setOutputParameters (const DirectionSpecificStreamParameters & parameters)
References outputParameters_.
void portaudio::StreamParameters::setSampleRate (double sampleRate)
Sets the requested sample rate. If this sample rate isn't supported by the hardware, the Stream will fail to open. The real-life sample rate used might differ slightly due to imperfections in the sound card hardware; use Stream::sampleRate() to retreive the best known estimate for this value.
References sampleRate_.
void portaudio::StreamParameters::setFramesPerBuffer (unsigned long framesPerBuffer)
Either the number of frames per buffer for a CallbackStream, or the preferred buffer granularity for a BlockingStream. See PortAudio documentation.
References framesPerBuffer_.
void portaudio::StreamParameters::setFlag (PaStreamFlags flag)
Sets the specified flag or does nothing when the flag is already set. Doesn't `unset' any previously existing flags (use clearFlags() for that).
References flags_.
void portaudio::StreamParameters::unsetFlag (PaStreamFlags flag)
Unsets the specified flag or does nothing if the flag isn't set. Doesn't affect any other flags.
References flags_.
void portaudio::StreamParameters::clearFlags ()
Clears or `unsets' all set flags.
References flags_.
bool portaudio::StreamParameters::isSupported () const
References inputParameters_, outputParameters_, portaudio::DirectionSpecificStreamParameters::paStreamParameters(), and sampleRate_.
DirectionSpecificStreamParameters & portaudio::StreamParameters::inputParameters ()
References inputParameters_.
Referenced by portaudio::MemFunCallbackStream< T >::open(), portaudio::InterfaceCallbackStream::open(), portaudio::FunCallbackStream::open(), portaudio::CFunCallbackStream::open(), and portaudio::BlockingStream::open().
const DirectionSpecificStreamParameters & portaudio::StreamParameters::inputParameters () const
References inputParameters_.
DirectionSpecificStreamParameters & portaudio::StreamParameters::outputParameters ()
References outputParameters_.
Referenced by portaudio::MemFunCallbackStream< T >::open(), portaudio::InterfaceCallbackStream::open(), portaudio::FunCallbackStream::open(), portaudio::CFunCallbackStream::open(), and portaudio::BlockingStream::open().
const DirectionSpecificStreamParameters & portaudio::StreamParameters::outputParameters () const
References outputParameters_.
double portaudio::StreamParameters::sampleRate () const
References sampleRate_.
Referenced by portaudio::MemFunCallbackStream< T >::open(), portaudio::InterfaceCallbackStream::open(), portaudio::FunCallbackStream::open(), portaudio::CFunCallbackStream::open(), and portaudio::BlockingStream::open().
unsigned long portaudio::StreamParameters::framesPerBuffer () const
References framesPerBuffer_.
Referenced by portaudio::MemFunCallbackStream< T >::open(), portaudio::InterfaceCallbackStream::open(), portaudio::FunCallbackStream::open(), portaudio::CFunCallbackStream::open(), and portaudio::BlockingStream::open().
PaStreamFlags portaudio::StreamParameters::flags () const
Returns all currently set flags as a binary combined integer value (PaStreamFlags). Use isFlagSet() to avoid dealing with the bitmasks.
References flags_.
Referenced by portaudio::MemFunCallbackStream< T >::open(), portaudio::InterfaceCallbackStream::open(), portaudio::FunCallbackStream::open(), portaudio::CFunCallbackStream::open(), and portaudio::BlockingStream::open().
bool portaudio::StreamParameters::isFlagSet (PaStreamFlags flag) const
Returns true if the specified flag is currently set or false if it isn't.
References flags_.
Member Data Documentation
DirectionSpecificStreamParameters portaudio::StreamParameters::inputParameters_ [private]
Referenced by inputParameters(), isSupported(), and setInputParameters().
DirectionSpecificStreamParameters portaudio::StreamParameters::outputParameters_ [private]
Referenced by isSupported(), outputParameters(), and setOutputParameters().
double portaudio::StreamParameters::sampleRate_ [private]
Referenced by isSupported(), sampleRate(), and setSampleRate().
unsigned long portaudio::StreamParameters::framesPerBuffer_ [private]
Referenced by framesPerBuffer(), and setFramesPerBuffer().
PaStreamFlags portaudio::StreamParameters::flags_ [private]
Referenced by clearFlags(), flags(), isFlagSet(), setFlag(), and unsetFlag().
The documentation for this class was generated from the following files:
StreamParameters.hxx
StreamParameters.cxx