PortAudioCpp: portaudio::HostApi Class Reference
portaudio::HostApi Class Reference
HostApi represents a host API (usually type of driver) in the System.
#include <HostApi.hxx>
Public Types
typedef System::DeviceIterator DeviceIterator
Public Member Functions
PaHostApiTypeId typeId () const
PaHostApiIndex index () const
const char * name () const
int deviceCount () const
DeviceIterator devicesBegin ()
DeviceIterator devicesEnd ()
Device & defaultInputDevice () const
Device & defaultOutputDevice () const
bool operator== (const HostApi &rhs) const
bool operator!= (const HostApi &rhs) const
Private Member Functions
HostApi (PaHostApiIndex index)
~HostApi ()
HostApi (const HostApi &)
HostApi & operator= (const HostApi &)
Private Attributes
const PaHostApiInfo * info_
Device ** devices_
Friends
class System
Detailed Description
HostApi represents a host API (usually type of driver) in the System.
A single System can support multiple HostApi's each one typically having a set of Devices using that HostApi (usually driver type). All Devices in the HostApi can be enumerated and the default input/output Device for this HostApi can be retreived.
Member Typedef Documentation
typedef System::DeviceIterator portaudio::HostApi::DeviceIterator
Constructor & Destructor Documentation
portaudio::HostApi::HostApi (PaHostApiIndex index) [explicit, private]
References portaudio::System::deviceByIndex(), deviceCount(), devices_, info_, and portaudio::System::instance().
portaudio::HostApi::~HostApi () [private]
References devices_.
portaudio::HostApi::HostApi (const HostApi &) [private]
Member Function Documentation
PaHostApiTypeId portaudio::HostApi::typeId () const
References info_.
Referenced by portaudio::AsioDeviceAdapter::AsioDeviceAdapter(), index(), and operator==().
PaHostApiIndex portaudio::HostApi::index () const
References typeId().
const char * portaudio::HostApi::name () const
References info_.
int portaudio::HostApi::deviceCount () const
References info_.
Referenced by devicesEnd(), and HostApi().
HostApi::DeviceIterator portaudio::HostApi::devicesBegin ()
References devices_, and portaudio::System::DeviceIterator::ptr_.
HostApi::DeviceIterator portaudio::HostApi::devicesEnd ()
References deviceCount(), devices_, and portaudio::System::DeviceIterator::ptr_.
Device & portaudio::HostApi::defaultInputDevice () const
References portaudio::System::deviceByIndex(), info_, and portaudio::System::instance().
Device & portaudio::HostApi::defaultOutputDevice () const
References portaudio::System::deviceByIndex(), info_, and portaudio::System::instance().
bool portaudio::HostApi::operator== (const HostApi & rhs) const
References typeId().
bool portaudio::HostApi::operator!= (const HostApi & rhs) const
HostApi& portaudio::HostApi::operator= (const HostApi &) [private]
Friends And Related Function Documentation
friend class System [friend]
Member Data Documentation
const PaHostApiInfo* portaudio::HostApi::info_ [private]
Referenced by defaultInputDevice(), defaultOutputDevice(), deviceCount(), HostApi(), name(), and typeId().
Device** portaudio::HostApi::devices_ [private]
Referenced by devicesBegin(), devicesEnd(), HostApi(), and ~HostApi().
The documentation for this class was generated from the following files:
HostApi.hxx
HostApi.cxx