PortAudioCpp: portaudio::System Class Reference
portaudio::System Class Reference
System singleton which represents the PortAudio system.
#include <System.hxx>
Classes
class DeviceIterator
Iterator class for iterating through all Devices in a System.
class HostApiIterator
Iterator class for iterating through all HostApis in a System.
Public Member Functions
HostApiIterator hostApisBegin ()
HostApiIterator hostApisEnd ()
HostApi & defaultHostApi ()
HostApi & hostApiByTypeId (PaHostApiTypeId type)
HostApi & hostApiByIndex (PaHostApiIndex index)
int hostApiCount ()
DeviceIterator devicesBegin ()
DeviceIterator devicesEnd ()
Device & defaultInputDevice ()
Device & defaultOutputDevice ()
Device & deviceByIndex (PaDeviceIndex index)
int deviceCount ()
void sleep (long msec)
int sizeOfSample (PaSampleFormat format)
Static Public Member Functions
static int version ()
static const char * versionText ()
static void initialize ()
static void terminate ()
static System & instance ()
static bool exists ()
static Device & nullDevice ()
Private Member Functions
System ()
~System ()
Static Private Attributes
static System * instance_ = NULL
static int initCount_ = 0
static HostApi ** hostApis_ = NULL
static Device ** devices_ = NULL
static Device * nullDevice_ = NULL
Detailed Description
System singleton which represents the PortAudio system.
The System is used to initialize/terminate PortAudio and provide a single acccess point to the PortAudio System (instance()). It can be used to iterate through all HostApi 's in the System as well as all devices in the System. It also provides some utility functionality of PortAudio.
Terminating the System will also abort and close the open streams. The Stream objects will need to be deallocated by the client though (it's usually a good idea to have them cleaned up automatically).
Constructor & Destructor Documentation
portaudio::System::System () [private]
Referenced by initialize().
portaudio::System::~System () [private]
Member Function Documentation
int portaudio::System::version () [static]
const char * portaudio::System::versionText () [static]
void portaudio::System::initialize () [static]
References deviceCount(), devices_, hostApiCount(), hostApis_, initCount_, instance(), instance_, nullDevice_, and System().
void portaudio::System::terminate () [static]
References deviceCount(), devices_, hostApiCount(), hostApis_, initCount_, instance(), instance_, and nullDevice_.
System & portaudio::System::instance () [static]
References exists(), and instance_.
Referenced by portaudio::HostApi::defaultInputDevice(), portaudio::HostApi::defaultOutputDevice(), portaudio::DirectionSpecificStreamParameters::device(), deviceByIndex(), portaudio::HostApi::HostApi(), portaudio::Device::hostApi(), initialize(), portaudio::Device::isSystemDefaultInputDevice(), portaudio::Device::isSystemDefaultOutputDevice(), and terminate().
bool portaudio::System::exists () [static]
References instance_.
Referenced by portaudio::Stream::close(), instance(), and portaudio::AutoSystem::~AutoSystem().
System::HostApiIterator portaudio::System::hostApisBegin ()
References hostApis_, and portaudio::System::HostApiIterator::ptr_.
System::HostApiIterator portaudio::System::hostApisEnd ()
References hostApiCount(), hostApis_, and portaudio::System::HostApiIterator::ptr_.
HostApi & portaudio::System::defaultHostApi ()
References hostApis_.
HostApi & portaudio::System::hostApiByTypeId (PaHostApiTypeId type)
References hostApis_.
HostApi & portaudio::System::hostApiByIndex (PaHostApiIndex index)
References hostApiCount(), and hostApis_.
Referenced by portaudio::Device::hostApi().
int portaudio::System::hostApiCount ()
Referenced by hostApiByIndex(), hostApisEnd(), initialize(), and terminate().
System::DeviceIterator portaudio::System::devicesBegin ()
References devices_, and portaudio::System::DeviceIterator::ptr_.
System::DeviceIterator portaudio::System::devicesEnd ()
References deviceCount(), devices_, and portaudio::System::DeviceIterator::ptr_.
Device & portaudio::System::defaultInputDevice ()
Returns the System's default input Device, or the null Device if none was available.
References deviceByIndex().
Device & portaudio::System::defaultOutputDevice ()
Returns the System's default output Device, or the null Device if none was available.
References deviceByIndex().
Device & portaudio::System::deviceByIndex (PaDeviceIndex index)
Returns the Device for the given index. Will throw a paInternalError equivalent PaException if the given index is out of range.
References deviceCount(), devices_, instance(), and nullDevice().
Referenced by defaultInputDevice(), portaudio::HostApi::defaultInputDevice(), defaultOutputDevice(), portaudio::HostApi::defaultOutputDevice(), portaudio::DirectionSpecificStreamParameters::device(), and portaudio::HostApi::HostApi().
int portaudio::System::deviceCount ()
Referenced by deviceByIndex(), devicesEnd(), initialize(), and terminate().
Device & portaudio::System::nullDevice () [static]
References nullDevice_.
Referenced by deviceByIndex().
void portaudio::System::sleep (long msec)
int portaudio::System::sizeOfSample (PaSampleFormat format)
Member Data Documentation
System * portaudio::System::instance_ = NULL [static, private]
Referenced by exists(), initialize(), instance(), and terminate().
int portaudio::System::initCount_ = 0 [static, private]
Referenced by initialize(), and terminate().
HostApi ** portaudio::System::hostApis_ = NULL [static, private]
Referenced by defaultHostApi(), hostApiByIndex(), hostApiByTypeId(), hostApisBegin(), hostApisEnd(), initialize(), and terminate().
Device ** portaudio::System::devices_ = NULL [static, private]
Referenced by deviceByIndex(), devicesBegin(), devicesEnd(), initialize(), and terminate().
Device * portaudio::System::nullDevice_ = NULL [static, private]
Referenced by initialize(), nullDevice(), and terminate().
The documentation for this class was generated from the following files:
System.hxx
System.cxx