PortAudioCpp: portaudio::AutoSystem Class Reference
portaudio::AutoSystem Class Reference
A RAII idiom class to ensure automatic clean-up when an exception is raised.
#include <AutoSystem.hxx>
Public Member Functions
AutoSystem (bool initialize=true)
~AutoSystem ()
void initialize ()
void terminate ()
Detailed Description
A RAII idiom class to ensure automatic clean-up when an exception is raised.
A simple helper class which uses the 'Resource Acquisition is Initialization' idiom (RAII). Use this class to initialize/terminate the System rather than using System directly. AutoSystem must be created on stack and must be valid throughout the time you wish to use PortAudioCpp. Your 'main' function might be a good place for it.
To avoid having to type portaudio::System::instance().xyz() all the time, it's usually a good idea to make a reference to the System which can be accessed directly.
    /// portaudio::AutoSys autoSys;
    /// portaudio::System &sys = portaudio::System::instance();
    ///
Constructor & Destructor Documentation
portaudio::AutoSystem::AutoSystem (bool initialize = true) [inline]
References initialize().
portaudio::AutoSystem::~AutoSystem () [inline]
References portaudio::System::exists(), and terminate().
Member Function Documentation
void portaudio::AutoSystem::initialize () [inline]
Referenced by AutoSystem().
void portaudio::AutoSystem::terminate () [inline]
Referenced by ~AutoSystem().
The documentation for this class was generated from the following file:
AutoSystem.hxx