PortAudioCpp: portaudio::Device Class Reference
portaudio::Device Class Reference
Class which represents a PortAudio device in the System.
#include <Device.hxx>
Public Member Functions
PaDeviceIndex index () const
const char * name () const
int maxInputChannels () const
int maxOutputChannels () const
PaTime defaultLowInputLatency () const
PaTime defaultHighInputLatency () const
PaTime defaultLowOutputLatency () const
PaTime defaultHighOutputLatency () const
double defaultSampleRate () const
bool isInputOnlyDevice () const
bool isOutputOnlyDevice () const
bool isFullDuplexDevice () const
bool isSystemDefaultInputDevice () const
bool isSystemDefaultOutputDevice () const
bool isHostApiDefaultInputDevice () const
bool isHostApiDefaultOutputDevice () const
bool operator== (const Device &rhs)
bool operator!= (const Device &rhs)
HostApi & hostApi ()
const HostApi & hostApi () const
Private Member Functions
Device (PaDeviceIndex index)
~Device ()
Device (const Device &)
Device & operator= (const Device &)
Private Attributes
PaDeviceIndex index_
const PaDeviceInfo * info_
Friends
class System
Detailed Description
Class which represents a PortAudio device in the System.
A single physical device in the system may have multiple PortAudio Device representations using different HostApi 's though. A Device can be half-duplex or full-duplex. A half-duplex Device can be used to create a half-duplex Stream. A full-duplex Device can be used to create a full-duplex Stream. If supported by the HostApi, two half-duplex Devices can even be used to create a full-duplex Stream.
Note that Device objects are very light-weight and can be passed around by-value.
Constructor & Destructor Documentation
portaudio::Device::Device (PaDeviceIndex index) [explicit, private]
References info_.
portaudio::Device::~Device () [private]
portaudio::Device::Device (const Device &) [private]
Member Function Documentation
PaDeviceIndex portaudio::Device::index () const
References index_.
Referenced by portaudio::AsioDeviceAdapter::AsioDeviceAdapter(), portaudio::AsioDeviceAdapter::inputChannelName(), portaudio::AsioDeviceAdapter::outputChannelName(), portaudio::DirectionSpecificStreamParameters::setDevice(), and portaudio::AsioDeviceAdapter::showControlPanel().
const char * portaudio::Device::name () const
References info_.
int portaudio::Device::maxInputChannels () const
References info_.
Referenced by isFullDuplexDevice(), and isOutputOnlyDevice().
int portaudio::Device::maxOutputChannels () const
References info_.
Referenced by isFullDuplexDevice(), and isInputOnlyDevice().
PaTime portaudio::Device::defaultLowInputLatency () const
References info_.
PaTime portaudio::Device::defaultHighInputLatency () const
References info_.
PaTime portaudio::Device::defaultLowOutputLatency () const
References info_.
PaTime portaudio::Device::defaultHighOutputLatency () const
References info_.
double portaudio::Device::defaultSampleRate () const
References info_.
bool portaudio::Device::isInputOnlyDevice () const
References maxOutputChannels().
bool portaudio::Device::isOutputOnlyDevice () const
References maxInputChannels().
bool portaudio::Device::isFullDuplexDevice () const
References maxInputChannels(), and maxOutputChannels().
bool portaudio::Device::isSystemDefaultInputDevice () const
References portaudio::System::instance().
bool portaudio::Device::isSystemDefaultOutputDevice () const
References portaudio::System::instance().
bool portaudio::Device::isHostApiDefaultInputDevice () const
References hostApi().
bool portaudio::Device::isHostApiDefaultOutputDevice () const
References hostApi().
bool portaudio::Device::operator== (const Device & rhs)
References index_.
bool portaudio::Device::operator!= (const Device & rhs)
HostApi & portaudio::Device::hostApi ()
References portaudio::System::hostApiByIndex(), info_, and portaudio::System::instance().
Referenced by portaudio::AsioDeviceAdapter::AsioDeviceAdapter(), isHostApiDefaultInputDevice(), and isHostApiDefaultOutputDevice().
const HostApi & portaudio::Device::hostApi () const
References portaudio::System::hostApiByIndex(), info_, and portaudio::System::instance().
Device& portaudio::Device::operator= (const Device &) [private]
Friends And Related Function Documentation
friend class System [friend]
Member Data Documentation
PaDeviceIndex portaudio::Device::index_ [private]
Referenced by index(), and operator==().
const PaDeviceInfo* portaudio::Device::info_ [private]
Referenced by defaultHighInputLatency(), defaultHighOutputLatency(), defaultLowInputLatency(), defaultLowOutputLatency(), defaultSampleRate(), Device(), hostApi(), maxInputChannels(), maxOutputChannels(), and name().
The documentation for this class was generated from the following files:
Device.hxx
Device.cxx